### PR TITLE
Render icons on blank start events

### LINKED ISSUE #12: Support icons on blank start events
__What should we do?__

Be able to render icons on (blank) start events.

__Why should we do it?__

Support inbound connectors.

### PR DESCRIPTION
**Pull request by nikku**
Icons can be rendered on blank start events:

screenshot lj39gn

Closes #12

### CODE REVIEW

**Comment by marstamm** [comment]
The description of this PR suggests that this should only work on blank start events. Is that correct?

On non-blank start events, the normal BPMN symbol is still rendered below the icon.
image

We should be consistent and either remove the default symbol or only allow custom Icons on none-events

**Comment by nikku** [comment]
Good catch. Will fix the PR accordingly.

**Comment by nikku** [comment]
Addressed with https://github.com/bpmn-io/element-template-icon-renderer/pull/13/commits/1598998a257d43fc126541dc4d743c6efdcd596d:

image

**Review by marstamm — APPROVED** [review]
🚀

**Pull request merged**
