### PR TITLE
Forced icon sizing

### LINKED ISSUE #4: Enforce rectangular icon size
__Is your feature request related to a problem? Please describe__

Icons shall be SVGs and thus can are decently scalable. In fact, scaling icons up and down on our end could help our users to choose icons that fit best into the existing iconography. 

__Describe the solution you'd like__

* [ ] Mandate fixed 18x18, rectangular icon size ([as documented](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/#icons))

__Describe alternatives you've considered__

Given the current approach icons can span the whole task; if we want to go that route we should stay off limits.

__Additional context__

Sizing icons correctly can be cumbersome, especially as [documentation](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/#icons) can easily be missed.

### PR DESCRIPTION
**Pull request by nikku**
This enforces an icon size of `18x18` (as [documented](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/#icons)).
 
image

Closes #4

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Should we update the docs then? It's not a recommendation then anymore. 🙂

**Comment by nikku** [comment]
We don't have to, but we could. If we settle down on this :).

**Comment by marstamm** [comment]
I think it makes sense to force a sensible Icon size. Only issue I see is that text is harder to read (see the camunda logo). But that's an edge case, so +1 from my side.
We should make it clear in the docs that the icon will be scaled to fit within 18x18 (canvas) and 32x32 ([properties panel header](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/650))

**Review by marstamm — APPROVED** [review]

**Comment by nikku** [comment]
Documentation follow-up: https://github.com/camunda/camunda-platform-docs/pull/907

**Pull request merged**
